### ISSUE TITLE
[BUG] Can't set size of featured-image

### ISSUE THREAD

**Issue by mwolfaardt** [sunt-programator/CodeIT#78] opened 2021-01-13 07:22 UTC
## Describe the bug

I am unable to set the size of the featured-image causing the image to display a massive oversized image

## Expected behavior

Have auto scale, or guidelines about what size the image should be. 

## Build Environment

- OS: Windows 10
- Theme version : latest

**Comment by victor-pogor** [comment] 2021-02-17 17:45
Hi, @mwolfaardt.

I can't reproduce your issue. I saw that the feature image is auto-scaled.

![image](https://user-images.githubusercontent.com/24962085/108245057-86f20200-7158-11eb-8599-5787dd395ff9.png)

**Comment by victor-pogor** [comment] 2021-02-28 09:29
Closed as need more details to reproduce this issue.

**Closed by victor-pogor** 2021-02-28 09:29 UTC
Labels: bug
